add react seminar backend
wafflestudio/waffle-world pull request #151
Opened 2023-11-11 08:20 UTC by joongwon

- 2023 리액트 세미나 백엔드 추가

android-project-backend에서 무지성 복붙했습니다.
대충 sqlite + nodejs라는 구조도 비슷하고 앱 사이즈도 비슷할거라 리소스 세팅도 똑같이 해놓으면 될 거라고 생각합니다.
하나하나 뜯어보기엔 시간도 없고 머리도 아파서 잠깐 미뤄두도록 하겠습니다.

2023-11-11 08:44 UTC, davin111 requested changes

2023-11-11 08:44 UTC, davin111 commented on apps/seminar/react-project-backend/react-project-backend.yaml
진짜 무지성 복붙이긴 한데요 ㅋㅋㅋ android 는 k8s resources 설정 하기 전에 올라간 yaml 이고 현재는 pod 0개인 상태라, resources 설정이 없습니다. 그래서 참고로 삼으실 링크는 최근에 생성된 다른 application 을 드렸던 거예요. 그 밖에도 조금씩 달라진 부분들이 있으니 확인 부탁드립니다.

2023-11-11 09:35 UTC, davin111 commented on apps/seminar/react-project-backend/react-project-backend.yaml
@joongwon 아래 것도 체크해주세요.

    spec:
      nodeSelector:
        phase: prod
      tolerations:
        - effect: NoSchedule
          key: phase
          operator: Equal
          value: prod

어떤 k8s node 에 배치할지 정하는 것입니다.

2023-11-11 09:38 UTC, davin111 reviewed
seminar-react-api.wafflestudio.com 를 k8s load balancer 에 연결하는 것은 Route53 에서 하면 되는데, 요건 제가 했어요~ https://us-east-1.console.aws.amazon.com/route53/v2/hostedzones?region=ap-northeast-2#ListRecordSets/Z04088332GMJ43MZ59UNN

2023-11-11 09:38 UTC, davin111 commented on apps/seminar/react-project-backend/react-project-backend.yaml
> +            memory: 128Mi
어쩌면 128Mi 가 조금 부족할 수 있겠다는 생각도 드는데, 일단 해보고 grafana.wafflestudio.com 에서 모니터링 추후 해보면 될 거 같습니다.

2023-11-12 03:09 UTC, joongwon commented on apps/seminar/react-project-backend/react-project-backend.yaml
오잉 nodeSelector 썼다고 생각했는데 빼먹었군요...

2023-11-15 08:04 UTC, davin111 approved these changes
LGTM

2023-11-15 08:04 UTC, merged