Add feelin-social-dev to K8S cluster
wafflestudio/waffle-world pull request #25
Opened 2022-12-24 00:03 UTC by yeonsumia

2022-12-26 13:08 UTC, YeonghyeonKO approved these changes
manifest에는 문제 없는 것 같고, Deployment/Service/VirtualService 오브젝트도 잘 생성되는 것 같은데 @davin111 어떻게 보십니까??!

2022-12-27 09:14 UTC, davin111 requested changes

2022-12-27 09:14 UTC, davin111 commented on apps/feelin-dev/feelin-social-server/feelin-social-server.yaml
> +    - feelin-api-dev.wafflestudio.com
feelin-api-dev.wafflestudio.com 는 feelin-core-server 에 대응하는 호스트이고,

feelin-social-api-dev.wafflestudio.com 가 맞을 거 같습니다.

https://wafflestudio.slack.com/archives/C031ECCFP2B/p1670333877507969?thread_ts=1670304137.514079&cid=C031ECCFP2B

2022-12-29 06:19 UTC, davin111 approved these changes
LGTM

2022-12-30 03:51 UTC, james0248 approved these changes

2022-12-30 03:51 UTC, merged