Add feelin-web-dev to K8S cluster
wafflestudio/waffle-world pull request #37
Opened 2023-01-25 15:29 UTC by jm020827

2023-01-25 15:53 UTC, james0248 requested changes

2023-01-25 15:53 UTC, james0248 commented on apps/feelin-dev/feelin-web/feelin-web.yaml
> +  - feelin-web-dev.wafflestudio.com
feeling-web-dev 가 아니라 feelin-dev 입니다

2023-01-25 18:41 UTC, davin111 commented on apps/feelin-dev/feelin-web/feelin-web.yaml
> +  type: NodePort
이거 그냥 ClusterIP 로 해도 될 거 같습니다. 새로 만드는 것은 그렇게 하고 있고 나중에 일괄 바꾸려고요.

2023-01-25 18:42 UTC, davin111 reviewed
얘는 별도로 aws 리소스 써서 pod 에 권한 부여해줄 필요 한 거 없나요?

2023-01-26 10:03 UTC, jm020827 commented
네 현재는 딱히 없습니다!

2023-01-26 10:31 UTC, davin111 commented on apps/feelin-dev/feelin-web/feelin-web.yaml
> +      - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/feelin-dev/feelin-web:6
지금은 보니까 최신 버전 7이던데 바꿔야겠네요.

2023-01-26 10:32 UTC, davin111 requested changes

2023-01-26 10:32 UTC, davin111 commented on apps/templates/feelin-web-dev.yaml
> +  name: feelin-web
이거 이름 feelin-web-dev 로 해주세요. prod 가 feelin-web 으로 이름이 만들어지면 좋을 거 같습니다.

2023-01-26 10:33 UTC, davin111 commented on apps/templates/feelin-web-dev.yaml
> +  name: feelin-web
<img width="340" alt="스크린샷 2023-01-26 19 33 09" src="https://user-images.githubusercontent.com/35535636/214814655-a4705ff4-6023-4462-8fea-0d43fd2f5ffe.png">

참고로 이렇게 보이는 이름입니다.

2023-01-26 10:34 UTC, davin111 commented
위 2개만 딱 수정하시면 칼 approve 드릴 수 있습니다.

2023-01-26 12:11 UTC, jm020827 commented
수정했습니다!

2023-01-26 12:31 UTC, davin111 approved these changes

2023-01-26 14:06 UTC, james0248 approved these changes

2023-01-26 14:28 UTC, merged